; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = data

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = spiffs
build_flags =
	-D X9C103S_CS_PIN=4
	-D X9C103S_INC_PIN=5
	-D X9C103S_UD_PIN=6
	-D COOLANT_FAN_LOW_PIN=7
	-D COOLANT_FAN_HIGH_PIN=15

monitor_speed = 115200
upload_port = COM16
monitor_port = COM24

lib_deps = 
	https://github.com/Modellfan/ACAN2515
	arkhipenko/TaskScheduler@^3.8.5
	FastLED/FastLED@^3.9.15


	;https://github.com/Modellfan/acan-esp32
	;https://github.com/Modellfan/esp32_can
	;https://github.com/collin80/can_common


